name = "Escape"
uuid = "c9e4727e-aca6-11e8-18a9-b13bcfc7f449"
authors = ["Daniel Habermann <daniel.habermann@uni-due.de>"]
version = "0.1.0"

[deps]
BioSequences = "7e6ae17a-c86d-528c-b3b9-7f778a29fe59"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
